### ISSUE TITLE
ARServer crashing with object types from arcor2_kinali

### ISSUE THREAD

**Issue by NelaMm** [robofit/arcor2#341]
**Description**
New AR Editor version 0.10.1 doesn't work after upload kinali services. Arserver crashes after upload these services (added log below). 

**Found in version**
AREditor version 0.10.1
arcor2_arserver 0.10.0
arcor2_upload_kinali 0.9.1

**Perform the following steps reproduce the bug**
- Run docker by docker-compose
- Run arcor2_upload_kinali for uploading services
- Run AREditor

**Observed results**
AREditor can not connect.

**Expected results**
AREditor succesfully connected and objects succesfully added.

**Related data**
[log.txt](https://github.com/robofit/arcor2/files/5457484/log.txt)

**Comment by ZdenekM** [comment]
Thanks for the report. We will release fixed images ASAP.

Just a note (you probably know, but it is not mentioned in your steps to reproduce): after uploading object types (running arcor2_upload_kinali) you have to restart ARServer - for now, it downloads and analyzes object types only on start-up.

**Comment by ZdenekM** [comment]
Btw, if you want to continue with the testing, you can update [KinaliRobot](https://github.com/robofit/arcor2/blob/master/src/python/arcor2_kinali/object_types/kinali_robot.py)'s sources in the Project service.  The problem was there and is already fixed. At the same time, error handling in the ARServer was improved, as well as testing so this should not happen again hopefully. @Kapim will release new versions of arcor2_arserver and arcor2_upload_kinali today or tomorrow in the morning.

**Comment by NelaMm** [comment]
Ok. Thank you.

**Comment by ZdenekM** [comment]
Please try now with arcor2_arserver 0.10.1, arcor2_build 0.9.2 and arcor2_kinali 0.9.2. The root cause lied in one transitive dependency - we updated the library version and the problem seems to be gone.

**Comment by NelaMm** [comment]
Seems to be OK.

**Comment by ZdenekM** [comment]
Glad to hear that! :-)
