### ISSUE TITLE
Project debugging

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2#607]
With an open project, it is possible to run a selected action, which either works for projects with and without logic. In order to simplify debugging, it would be nice if we can set a "breakpoint" on a certain AP or action. It probably makes more sense to set a breakpoint on action than on AP, but there might be projects with only APs defined. Another thing is to allow stepping over actions. The thing is whether this will be implemented solely in the ARServer (easier to implement, more flexible, allows "step back" etc.), or on the Execution service (harder to implement, less flexible, but could work also for projects without logic/actions).

**Comment by martincervinka** [comment]
The requirement is for Execution Web API because we would like to use the API from WebUI to debug the projects. WebUI does not have a dependency on ARServer and this should not be changed. Can you define a proposal for API change on our Confluence, please?

The API must allow this functionality from WebUI
- Step over Actions
    - Project execution is paused before any Action (any method in object_type defined as action) in the script.
- Break on Action Point
    -  Project execution is paused when one of the parameters from any Action are joints or pose of defined AP.
